<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Layout para SM-->
            <div class="col d-block d-md-none bg-transparent">

                <div class="areas p-1">
                    <div class="row">
                        <div class="col-3 ">
                            <img src="/Front_end/foto-perfil.png" class="mt-3" alt="">
                        </div>
                        <div class="col-9">
                            <p class="info-nome">Thiago André</p>
                            <div class="clearfix">
                                <div style="float: left;" class="mr-2">
                                    <p class="no-margin size8">recados</p>
                                    <img src="/Front_end/icons/recados.png" alt=""> 2
                                </div>
                                <div style="float: left;" class="mr-2">
                                    <p class="no-margin size8">fotos</p>
                                    <img src="/Front_end/icons/fotos.png" alt=""> 2
                                </div>
                                <div style="float: left;" class="mr-2">
                                    <p class="no-margin size8">vídeos</p>
                                    <img src="/Front_end/icons/videos.png" alt=""> 2
                                </div>
                                <div style="float: left;" class="mr-2">
                                    <p class="no-margin size8">fãs</p>
                                    <img src="/Front_end/icons/fas.png" alt=""> 2
                                </div>
                                <br><br>


                                <div class="row pl-3">
                                    <div class="menu-geral">
                                        <p class="no-margin texto-menu">confiável</p>
                                        <img class="no-margin mr-1" src="/Front_end/icons/confiavel.png" alt="">
                                    </div>
                                    <div class="menu-geral">
                                        <p class="no-margin texto-menu">legal</p>
                                        <img class="no-margin mr-1" src="/Front_end/icons/legal.png" alt="">
                                    </div>
                                    <div class="menu-geral">
                                        <p class="no-margin texto-menu">sexy</p>
                                        <img class="no-margin mr-1" src="/Front_end/icons/coracoes.png" alt="">
                                    </div>


                                </div>

                            </div>
                        </div>
                        <div class="col-3 ">

                        </div>
                    </div>
                </div>

                <div class="col areas p-2 mt-2">
                    <div id="social" class="mt-2">
                        <p class="no-margin">social</p>
                    </div>


                    <div id="social-info">
                        <div class="no-margin social-info1 py-2">
                            <p class="no-margin">aniversario: 1 de janeiro de 1999</p>
                        </div>
                        <div class="no-margin social-info2 py-2">
                            <p class="no-margin">relacionamento: solteiro(a)</p>
                        </div>
                        <div class="no-margin social-info1 py-2">
                            <p class="no-margin">país: Brasil</p>
                        </div>
                    </div>
                </div>

                <div class="col-md mt-2" style="padding: 0;">
                    <div class="bg-white p-2" style="border-radius: 10px;">
                        <h4>meus amigos <span>(0)</span></h4>
                        <div class="mt-1 p-1" style="background: #eef7ff;">
                            <p class="no-margin" style="font-size: 0.8em;">você ainda não adicionou nenhum amigo</p>
                        </div>
                        <div class="campos mt-2" style="border-bottom: 1px solid white;">
                            <div class="mb-1"></div>
                            <button class="btn btn-sm botao">
                                <a class="texto-botao" href="encontrar_amigos">Adicionar amigos</a>
                            </button>
                        </div>
                    </div>

                    <div class="bg-white p-2 mt-2" style="border-radius: 10px;">
                        <h4>minhas comunidades <span>(0)</span></h4>

                        <div class="campos mt-2" style="border-bottom: 1px solid white;">
                            <div class="mb-1"></div>
                            <button class="btn btn-sm botao">
                                <a class="texto-botao" href="pesquisa_comunidade">Adicionar comunidades</a>
                            </button>
                        </div>
                    </div>

                </div>

            </div>


            <!-- Fim Layout para SM-->

            <?php 
                if($_GET['id'] == $_SESSION['id']){
                    require("App\Views\componentes\barra_esquerda.phtml");
                } else {
                    require("App\Views\componentes\barra_esquerda_perfil_others.phtml");
                }
             ?>

            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1 d-none d-md-block">
                <div class="bg-white p-2" id="info-gerais">
                    <h3 style="font-weight: 400;"><?= $this->view->info_usuario['nome'] ?></h3>
                    <div class="p-1">
                        <span><a href="">Início</a></span> <span style="color: gray;">> Meu perfil</span>
                    </div>


                    <div class="row mx-2 mt-2 p-1" id="frase-perfil">    
                        
                                <p id="p-frase" class="no-margin pt-1"><?php 
                                if($_GET['id'] == $_SESSION['id']){ ?>
                                    <div class="col-8">
                                <p id="p-frase" class="no-margin pt-1"><?php 
                                if($this->view->info_usuario['frase'] == null || $this->view->info_usuario['frase'] == ''){  
                                    echo 'Qual é a sua frase de perfil?';}  else{
                                     echo $this->view->info_usuario['frase']; }  
                                     ?>
                                </p>
                        </div>
                        <div class="col-4">
                        <button onclick=" setFrase()" style="height:30px; float:right" class="btn btn-sm botao">
                            <a  class="texto-botao">Editar</a>
                        </button>
                        </div>
                               <?php  } else{ ?>
                                    <div class="col-8">
                                    <p id="p-frase" class="no-margin pt-1"> <?php  
                                    if($this->view->info_usuario['frase'] != null || $this->view->info_usuario['frase'] != '')
                                    {
                                     echo $this->view->info_usuario['frase']; }  
                                     ?>
                                    </p>
                                    </div>
                               <?php } ?> 

                                
                                </p>
                        
                    </div>

                   

                    <div class="row ml-2 mt-3 campos py-2 mr-2">
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">recados</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/recados.png" width="25%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">fotos</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/fotos.png" width="50%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">videos</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/videos.png" width="40%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">fas</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/fas.png" width="52%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">mensagens</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/mensagens.png" width="25%" alt="">0
                        </div>
                    </div>
                    <div class="row ml-2 mt-3 mb-3 mr-2 pb-2" style="border-bottom:1px solid #b7e8fa">
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">confiável</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/confiavel.png" alt="">
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">legal</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/legal.png" alt="">
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">sexy</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/coracoes.png" alt="">
                        </div>

                    </div>


                    <div id="social" class="mt-2">
                        <p class="no-margin">social</p>
                    </div>


                    <div id="social-info">
                        <div class="no-margin social-info1 py-2">
                            <p class="no-margin">aniversário: <?= $this->view->info_usuario['data']; ?> </p>
                        </div>
                       
                        <div class="no-margin social-info2 py-2">
                            <p class="no-margin">país: Brasil</p>
                        </div>
                    </div>


                </div>


            </div>

            <!--Fim Centro-->

            <?php require_once('App/Views/componentes/barra_direita.phtml'); ?>


        </div>
    </div>

    


    <script>
        
        function setFrase(){
            $('#frase-perfil').html('<div><form action="/frase" method="post"> <input type="text" name="frase" class="mb-1" style="width:100%; height:25px">  <button type="submit" style="height:30px;" class="btn btn-sm botao"><a class="texto-botao">atualizar</a></button><button style="height:30px;" class="btn btn-sm botao"><a href="/perfil" class="texto-botao">cancelar</a></button> </form></div>');
        }
        
    </script>
                  