<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <?php require_once('App/Views/componentes/barra_esquerda.phtml');?>
            
        <!--Coluna Centro-->
        <div class="col-md-9 bg-transparent mr-1 mt-2">
            <div class="areas p-2">

                <form class="p-2 mb-1" action="/setRecado?id=<?= $_GET['id'] ?>" method="post">
                    <div style="border-bottom: 1px solid rgba(128, 128, 128, 0.116);">
                        <textarea placeholder="digite o texto ou cole HTML" name="recado" rows="4" cols="75"></textarea>
                    </div>

                    <div class="mx-2 ">
                    <button type="submit" class="btn btn-sm botao shadow-sm mb-3">
                        <a class="texto-botao">enviar recado</a>
                    </button>

                </div>
                </form>

                

            </div>

            <div class="bg-white clearfix mt-2 mb-3" style="border-radius: 5px;">
                <div class=" ml-2" style="border-bottom: 1px solid rgba(128, 128, 128, 0.24);">
                    <h3>Minha página de recados (0)</h3>
                    <div class="p-1 mb-2">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> <span
                            style="color: gray; font-size: 0.9em;">> Minha página de recados</span>
                    </div>
                </div>


             
             <?php 
                 foreach($this->view->recados as $key=>$recados) { ?>

               <div class="px-2 mt-2 my-3 clearfix" style=" border-bottom:1px solid #b7e8fa">
               
                    <div style="float:left;">
                    <img src="/uploads/<?= $recados['image'] ?>"  width="85px" alt="">
                    </div>

                    <div class="ml-3" style="float:left" class="ml-2">
                        <p class="no-margin"><?= $recados['nome'] ?></p>
                        <p class="no-margin size8 ">
                            <?= $recados['recado'] ?>
                        </p>
                    </div>

                    <div style="float:right;" class=" ml-3 mt-4 pb-2 ">
                        <button class=" btn btn-sm botao"><a href="/acao?id=<?= $_GET['id']?>&acao=apagar&id_recado=<?=$key+1 ?>" class="texto-botao">apagar</a></button>
                    </div>

            </div>  
                

                <?php } ?> 

            </div>

                </div>
            </div>

        </div>



    </div>