<div class="container mt-2 " style="border-radius: 5%; ">

    <div class="row h-100">

        <!--Layout para SM-->

        <div class="col-12 d-md-none">

            <div class="areas p-2">
                <!--Foto e título-->
                <div class="row">  
                    <div class="col-3">
                        <img class="fix-size-img" src="/uploads_comunidade/<?= $this->view->comunidades[0]['imagem'] ?>" alt="">
                    </div>
                    <div class="col">
                        <a style="font-size: 1.3em;" href=""><?= $this->view->comunidades[0]['nome']?></a> <br>
                        
                            <?php if ($this->view->seguindo['num'] == 0) { ?>
                                    <button class="btn btn-sm botao mt-2">
                                <img src="/Front_end/icons/deixar.png" alt="">
                                <a href="/acao?acao=participar&id=<?= $_GET['id'] ?>" class="texto-botao">participar</a>
                            </button>
                                <?php  } else { ?> 
                                    <button class="btn btn-sm botao mt-2">
                                <img src="/Front_end/icons/deixar.png" alt="">
                                <a href="/acao?acao=deixar_de_participar&id=<?= $_GET['id'] ?>" class="texto-botao">deixar comunidade</a>
                            </button>
                                <?php } ?>
                        
                    </div>
                </div>
            </div>
            <!--Fim Foto e título-->


            <div class="areas p-2 mt-2">
                <!--Informações da comunidade-->
                <div class="bg-listrado-1 p-2">
                    <p class="no-margin size9 " style="color: rgb(104, 101, 101);">descrição:</p>
                    <p class="no-margin" style="font-weight: 500; color: rgb(124, 121, 121);">
                    <?= $this->view->comunidades[0]['descrição'] ?></p>
                </div>
                <div class="bg-listrado-2 p-2">
                    <p class="no-margin size9 color-gray">idioma:</p>
                    <p class="no-margin gray-and-bold">Português</p>
                </div>
                <div class="bg-listrado-1 p-2">
                    <p class="no-margin size9 color-gray">categoria: </p>
                    <p class="no-margin gray-and-bold"><?= $this->view->comunidades[0]['categoria'] ?></p>
                </div>
                <div class="bg-listrado-2 p-2">
                    <p class="no-margin size9 color-gray">dono:  </p>
                    <p class="no-margin gray-and-bold"><?php echo $this->view->comunidades[0]['dono'] ?></p>
                </div>
                <div class="bg-listrado-1 p-2">
                    <p class="no-margin size9 color-gray">tipo:</p>
                    <p class="no-margin gray-and-bold">pública</p>
                </div>
                <div class="bg-listrado-2 p-2">
                    <p class="no-margin size9 color-gray">local:</p>
                    <p class="no-margin gray-and-bold">Brasil</p>
                </div>
               

            </div>
            <!--Fim Informações da comunidade-->


        </div>

        <!-- Fim Layout para SM-->



        <?php require('App/Views/componentes/barra_esquerda_comunidade.phtml'); ?>

        <!--Coluna Centro-->
        <div class="col-md-7 bg-transparent mr-1">

            <div class="bg-white p-2  d-none d-md-block" id="info-gerais">
                <!--Infos Comunidade-->
                <h3 style="font-weight: 400;"><?= $this->view->comunidades[0]['nome'] ?></h3>
                <!--Titulo e mini-nav-->
                <div class="p-1" id="mini-nav">
                    <span><a href="/timeline">Início ></a></span>
                    <span><a href="/comunidades"> Comunidades </a></span>
                    <span style="color: gray;">> Meu perfil</span>
                </div>
                <!--fim Titulo e mini-nav-->


                <div class="mt-2">
                    <div class="no-margin  py-2">
                        <table style="width:100%">
                            <tr class="bg-listrado-1">
                                <td class="pr-3 pl-5 py-2 texto-info-comunidade" style="vertical-align: top;">descricao:</td>
                                <td class="size9 py-2"><?= $this->view->comunidades[0]['descrição'] ?>
                                </td>
                            </tr>
                            <tr class="bg-listrado-2">
                                <td class="pr-3 pl-5 py-2 texto-info-comunidade" style="vertical-align: top;">idioma:</td>
                                <td class="size9 py-2"> Português
                                </td>
                            </tr>
                            <tr class="bg-listrado-1">
                                <td class="pr-3 pl-5 py-2 texto-info-comunidade" style="vertical-align: top;">categoria:</td>
                                <td class="size9 py-2"> <?= $this->view->comunidades[0]['categoria'] ?>
                                </td>
                            </tr>
                            <tr class="bg-listrado-2">
                                <td class="pr-3 pl-5 py-2 texto-info-comunidade" style="vertical-align: top;">dono:</td>
                                <td class="size9 py-2"> <?php echo $this->view->comunidades[0]['dono'] ?>
                                </td>
                            </tr>
                            <tr class="bg-listrado-1">
                                <td class="pr-3 pl-5 py-2 texto-info-comunidade">tipo:</td>
                                <td class="size9 py-2"> pública
                                </td>
                            </tr>
                            <tr class="bg-listrado-2">
                                <td class="pr-3 pl-5 py-2 texto-info-comunidade">local:</td>
                                <td class="size9 py-2"> Brasil
                                </td>
                            </tr>
                            <tr class="bg-listrado-1">
                               
                            </tr>
                        </table>
                    </div>

                </div>


            </div>
            <!--Fim Infos Comunidade-->


            <div class="bg-white mt-2 p-2 areas mb-3">
                <!--fórum-->
                <strong class="size9">fórum</strong>
                <table style="width: 100%; margin: 0 auto;">
                    <thead>
                        <td style="padding: 10px;" class="td-left">
                            <p class="no-margin tabela-header">tópico</p>
                        </td>

                        <td style="padding: 10px;" class="td-right">
                            <p class="no-margin tabela-header">última postagem</p>
                        </td>
                    </thead>

                    <?php foreach ($this->view->lastTopics as $key => $topics) { ?> 
                        <tr class="bg-listrado-<?= $key % 2 == 0 ? '1' : '2' ?>">
                            <td class="td-left py-1"><a href="/topico?id=<?= $_GET['id'] ?>&id_topico=<?= $topics['id'] ?>"><?= $topics['topico'] ?></a></td>
                            <td class="td-right size9">
                                <p><?= $this->view->lastRespostaData[$key]['data']; ?></p>
                            </td>
                        </tr>
                    <?php }

                    ?>

                </table>

                <div class="campos clearfix">
                    <div style="float: left;">
                        <button class="btn btn-sm botao mt-2">
                            <a href="/novo_topico?id=<?= $_GET['id'] ?>" class="texto-botao">novo tópico</a>
                        </button>
                    </div>
                    <div style="float: right;" class="mt-2">
                        <a id="todos-topicos" href="/forum?id=<?= $_GET['id'] ?>">ver todos os tópicos >></a>
                    </div>
                </div>
            </div>
            <!--Fim fórum-->

        </div>

        <!--Fim Centro-->

        <!--Começo Coluna Direita-->
        <div class="col-md">
            <div class="col -md bg-white p-2" style="border-radius: 10px;">
                <h4>membros <span>(<?php print_r($this->view->total_membros) ?>)</span></h4>
                <?php if (isset($this->view->membros[0])) { ?>
                    <div class="row" style="margin:auto">

                        <?php
                        foreach ($this->view->membros as $membros) { ?>
                            <div class="col-4 p-2 galeria-element">
                                <img class="fix-size-img" src="/uploads/<?= $membros['image'] ?>" alt="">
                                <a href="/comunidade_page?id=<?= $membros['id'] ?>">
                                    <p class="no-margin size9 wrap" style="text-align: center;    line-height: 1"><?= $membros['nome'] ?></p>
                                </a>
                            </div>
                        <?php  } ?>
                    </div>
                <?php
                } else { ?>
                    <p class="size8">essa comunidade ainda não possui membros</p>
                <?php  }
                ?>

            </div>



        </div>
        <!--Fim Coluna Direita-->

    </div>
</div>