<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Layout para SM-->
            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1 d-md-none">
                <div class="bg-white p-2" id="info-gerais">

                    <h3>Comunidades</h3>
                    <div class="p-1 mb-2">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> <span style="color: gray; font-size: 0.9em;">> Comunidades</span>
                    </div>
                    <p class="size9">Compartilhe suas paixões. Conheça pessoas que têm interesses em comum. Troque idéias. Planeje eventos...</p>
                    <p class="size9">Você pode pesquisar comunidades ou criar sua própria comunidade.</p>

                </div>

            </div>

            <!--Fim Centro-->

            <!--Começo Coluna Direita-->
            <div class="col-md p-2 d-md-none " style="padding: 0;">

                <div class="bg-white p-2 mt-2" style="border-radius: 10px;">
                    <h4>todas as comunidades<span>(0)</span></h4>

                    <div class="campos mt-2" style="border-bottom: 1px solid white;">

                        <p class="no-margin mb-1" style="font-size:0.9em">pesquisar por nome:</p>
                        <input type="text" style="line-height: normal; width: 100%;">
                        <div class="row mt-2">
                            <div class="col-4">
                                <button style="display: block;" class="btn btn-sm botao mt-1">
                                    <a href="/pesquisa_comunidade" class="texto-botao">pesquisar</a>
                                </button>
                            </div>
                            <div class="col-8">
                                <button style="display: block;" class="btn btn-sm botao mt-1">
                                    <a class="texto-botao">criar comunidade</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!--Fim Coluna Direita-->
            <!--Fim Layout para SM-->

            <!--Coluna Esquerda-->
            <div class="col-md-2 d-none d-md-block" style="padding: 0;">
                <div class="bg-white p-2 mr-1 pt-4" style="border-radius: 7px;">
                    <div id="conteudo-esquerda" class="ml-1">
                        <div>
                            <img class="ml-2" src="/Front_end/foto-perfil.png" width="80%" alt="">
                            <p class="mt-2 mb-1 info-nome">Thiago André</p>
                            <div class="campos">
                                <div class="mt-2 mb-2">
                                    <span><img src="/Front_end/icons/perfil.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">perfil</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">recados</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/fotos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">fotos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/videos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">vídeos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/depoimentos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">depoimentos</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div class="campos">
                                <div class="mb-2">
                                    <h4>Apps</h4>
                                    <span><img src="/Front_end/icons/apps.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">adicionar apps</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div class="campos pb-2" style="border-bottom: 1px solid white;">
                                <div class="mt-2">
                                    <span><img src="/Front_end/icons/lista.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">listas</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/atualizaçoes.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">atualizações</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/configuracao.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">configurações</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1 d-none d-md-block">
                <div class="bg-white p-2" id="info-gerais">

                    <h3>Comunidades</h3>
                    <div class="p-1 mb-2">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> <span style="color: gray; font-size: 0.9em;">> Comunidades</span>
                    </div>
                    <div id="explorar" style="padding: 2px 5px;" class="mt-2">
                        <p class="no-margin">todas (1)</p>
                    </div>
                    <div style="border-bottom: 1px solid rgba(128, 128, 128, 0.253);"></div>
                    <h4 class="pl-1 mt-3">nome</h4>
                    <div class="p-2" style="background: #f0f7ff;">
                        <a href="">
                            <p style="display: inline;" class="no-margin">Eu odeio acordar cedo </p>
                        </a>
                    </div>

                </div>

            </div>

            <!--Fim Centro-->

            <!--Começo Coluna Direita-->
            <div class="col-md d-none d-md-block" style="padding: 0;">

                <div class="bg-white p-2 mt-2" style="border-radius: 10px;">
                    <h4>todas as comunidades<span>(0)</span></h4>

                    <div class="campos mt-2" style="border-bottom: 1px solid white;">

                        <p class="no-margin mb-1" style="font-size:0.9em">pesquisar por nome:</p>
                        <input type="text" style="line-height: normal; width: 100%;">
                        <div class="row">
                        <div class="col-lg-4">
                            <button style="display: block;" class="btn btn-sm botao mt-1">
                                <a href="/pesquisa_comunidade" class="texto-botao">pesquisar</a>
                            </button>
                        </div>
                        <div class="col-lg-8">
                            <button style="display: block;" class="btn btn-sm botao mt-1">
                                <a class="texto-botao">criar comunidade</a>
                            </button>
                        </div>
                    </div>
                    </div>
                </div>

            </div>
            <!--Fim Coluna Direita-->


        </div>
    </div>