<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Layout para SM-->



            <div class="col-12 d-md-none">
                <div class="areas p-2">
                    <div class="row">
                        <div class="col-3">
                            <img src="/public/img/logo-teste.jpg" alt="">
                        </div>
                        <div class="col p-3">
                            <a style="font-size: 1.3em;" href="">Eu odeio acordar cedo</a> <br>
                            <button class="btn btn-sm botao mt-2">
                                <img src="/Front_end/icons/deixar.png" alt="">
                                <a class="texto-botao">deixar comunidade</a>
                            </button>
                        </div>
                    </div>
                </div>

            </div>


            <!-- Fim Layout para SM-->

            <!--Coluna Esquerda-->


            <div class="col-md-2 d-none d-md-block" style="padding: 0;">
                <div class="bg-white p-2 mr-1 pt-4" style="border-radius: 7px;">
                    <div id="conteudo-esquerda">
                        <div>

                            <img class=" center" src="/Front_end/foto-perfil.png" alt="">

                            <p class="mt-2 mb-1 info-nome">Eu Odeio Acordar Cedo</p>
                            <div class="campos">
                                <div class=" mb-2">
                                    <span><img src="/Front_end/icons/participar.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">participar</p>
                                    </a> <br>
                                </div>
                            </div>

                            <span><img src="/Front_end/icons/forum.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">fórum</p>
                            </a> <br>
                            <span><img src="/Front_end/icons/enquetes.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">enquetes</p>
                            </a> <br>
                            <span><img src="/Front_end/icons/eventos.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">eventos</p>
                            </a> <br>
                            <span><img src="/Front_end/icons/membros.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">membros</p>
                            </a> <br>



                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col bg-transparent mr-1 mt-2">
                <div class="bg-white p-2  areas">

                    <!--Título e Nav-->
                    <h3 style="font-weight: 400;">Fórum</h3>
                    <div class="p-1" id="mini-nav">
                        <span><a href="">Início ></a></span>
                        <span><a href=""> Comunidades > </a></span>
                        <span><a href=""> Eu Odeio Acordar Cedo </a></span>
                        <span style="color: gray;">> Fórum</span>
                    </div>
                    <!--Fim Título e Nav-->


                    <!--Pesquisa-->
                    <div>
                        <span class="size9">pesquisar neste fórum:</span>
                        <span><input type="text"></span>
                        <span style="vertical-align: bottom;">
                            <button class="btn btn-sm botao mt-2">
                                <a class="texto-botao">pesquisar</a>
                            </button>
                        </span>
                    </div>

                    <div class="borda-top mt-1 mb-2">
                        <button class="btn btn-sm botao mt-2">
                            <a class="texto-botao">novo tópico</a>
                        </button>
                    </div>
                    <!--Fim Pesquisa-->


                    <!--Tópicos-->
                    <table style="width: 100%; margin: 0 auto;">
                        <thead>
                            <td class="td-left">
                                <p class="no-margin tabela-header" >tópico</p>
                            </td>

                            <td style="width: 12%;">
                                <p class="no-margin tabela-header" style="text-align: center;">autor</p>
                            </td>
                            <td style="width: 12%;">
                                <p class="no-margin tabela-header" style="text-align: center;">postagens</p>
                            </td>
                            <td style="width: 12%;" class="pb-1">
                                <p class="no-margin tabela-header" style="text-align: center;">última postagens</p>
                            </td>
                        </thead>

                        <tr class="bg-listrado-1">
                            <td class="td-left py-1"><a href="/topico">Madrugantes</a></td>
                            <td style="text-align: center;">Edson</td>
                            <td style="text-align: center;">4</td>
                            <td style="text-align: center;">14:39</td>
                        </tr>

                        <tr class="bg-listrado-2">
                            <td class="td-left py-1"><a href="/topico">Confessionário</a></td>
                            <td style="text-align: center;">Fabiana</td>
                            <td style="text-align: center;">105</td>
                            <td style="text-align: center;">14:36</td>
                        </tr>

                        <tr class="bg-listrado-1">
                            <td class="td-left py-1"><a href="/topico">Me adicionem</a></td>
                            <td style="text-align: center;">Nicolle</td>
                            <td style="text-align: center;">47</td>
                            <td style="text-align: center;">13:36</td>
                        </tr>

                        <tr class="bg-listrado-2">
                            <td class="td-left py-1"><a href="/topico">ORKUT VOLTOU</a></td>
                            <td style="text-align: center;">Black</td>
                            <td style="text-align: center;">101</td>
                            <td style="text-align: center;">12:45</td>
                        </tr>


                    </table>

                    
                    <!--Fim Tópicos-->

                    <div class="clearfix mt-1 borda-top">
                        
                        <div class="ml-2">
                            <button class="btn btn-sm botao mt-2">
                                <a class="texto-botao">novo tópico</a>
                            </button>
                        </div>
                    </div>

                </div>

            </div>

            <!--Fim Centro-->




        </div>
    </div>