<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Layout para SM-->

            

            <div class="col-12 d-md-none">
                <div class="areas p-2">
                    <div class="row">
                        <div class="col-3">
                            <img src="/public/img/logo-teste.jpg" alt="">
                        </div>
                        <div class="col p-3">
                            <a style="font-size: 1.3em;" href="">Eu odeio acordar cedo</a> <br>
                            <button class="btn btn-sm botao mt-2">
                                <img src="/Front_end/icons/deixar.png" alt="">
                                <a class="texto-botao">deixar comunidade</a>
                            </button>
                        </div>
                    </div>
                </div>
                
            </div>


            <!-- Fim Layout para SM-->

             <!--Coluna Esquerda-->

           <div class="col-md-2 d-none d-md-block" style="padding: 0;">
                <div class="bg-white p-2" style="border-radius: 7px;">
                    <div id="conteudo-esquerda">
                        <div>  
                            <img class="center fix-size-img" src="/uploads/<?= $this->view->comunidades[0]['imagem']?>" alt="">
                            <p class="mt-2 mb-1 info-nome"><?= $this->view->comunidades[0]['nome'] ?></p>

                            <div class="campos">
                                <div class=" mb-2">
                                    <span><img src="/Front_end/icons/participar.png" alt=""></span>

                                    <?php if($this->view->seguindo['num'] == 0){ ?>
                                        <a href="/acao?acao=participar&id=<?= $_GET['id'] ?>">
                                        <p class="no-margin texto-info">participar</p>
                                    </a> 
                                   <?php  } else { ?>
                                    <a href="/acao?acao=deixar_de_participar&id=<?= $_GET['id'] ?>">
                                        <p class="no-margin texto-info">deixar de participar</p>
                                    </a> 
                                <?php }
                                   
                                   ?>
                                    
                                    
                                    <br>
                                </div>
                            </div>

                            <div> <!--nav-esquerda-->
                                <span><img src="/Front_end/icons/forum.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">fórum</p>
                            </a> <br>
                            <span><img src="/Front_end/icons/enquetes.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">enquetes</p>
                            </a> <br>
                            <span><img src="/Front_end/icons/eventos.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">eventos</p>
                            </a> <br>
                            <span><img src="/Front_end/icons/membros.png" alt=""></span>
                            <a href="">
                                <p class="no-margin texto-info">membros</p>
                            </a> <br>
                            </div> <!--Fim nav-esquerda-->
                            
                        </div>
                    </div>
                </div>
            </div>

            <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col bg-transparent mr-1 mt-2">
                <div class="bg-white p-2  areas">
                    <h3 style="font-weight: 400;">Novo tópico</h3>
                    <div class="p-1" id="mini-nav">
                        <span><a href="/timeline">Início ></a></span> 
                        <span><a href="/comunidades"> Comunidades > </a></span> 
                        <span><a href="/comunidade_page?id=<?= $_GET['id'] ?>"> Eu Odeio Acordar Cedo </a></span> 
                        <span style="color: gray;">> Fórum</span>
                        <span style="color: gray;">> Novo tópico</span>
                    </div>

                    <form action="/criarTopico" method="post">
                    <input name="id" display="none" type="text" style="display:none" value="<?= $_GET['id'] ?>" >
                    <div class="no-margin social-info2 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Comunidade:</td>
                                <td class="size9"> Eu Odeio Acordar Cedo
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="no-margin social-info1 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Autor:</td>
                                <td class="size9"> Thiago André
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="no-margin social-info2 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Assunto:</td>
                                <td class="size9"> <input name="topico" type="text">
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="no-margin social-info1 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Mensagem:</td>
                                <td class="size9"> <textarea name="mensagem" id="" cols="70" rows="10"></textarea>
                                </td>
                            </tr>
                        </table>
                    </div>

                  

                    <div class="clearfix mt-1" style="border-top: 1px solid rgba(128, 128, 128, 0.144);">
                        <div style="float: left;">
                            <button class="btn btn-sm botao mt-2">
                                <a class="texto-botao">enviar</a>
                            </button>   
                        </div>
                        <div style="float: left;" class="ml-3">
                            <button class="btn btn-sm botao mt-2">
                                <a href="/comunidade_page?id=<?= $_GET['id'] ?>" class="texto-botao">cancelar</a>
                            </button>
                        </div>
                    </div>
                    </form>
                </div>
              

            </div>

            <!--Fim Centro-->

            


        </div>
    </div>