<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Layout para SM-->

            

            <div class="col-12 d-md-none">
                <div class="areas p-2">
                    <div class="row">
                        <div class="col-3">
                            <img src="/public/img/logo-teste.jpg" alt="">
                        </div>
                        <div class="col p-3">
                            <a style="font-size: 1.3em;" href="">Eu odeio acordar cedo</a> <br>
                            <button class="btn btn-sm botao mt-2">
                                <img src="/Front_end/icons/deixar.png" alt="">
                                <a class="texto-botao">deixar comunidade</a>
                            </button>
                        </div>
                    </div>
                </div>
                
            </div>


            <!-- Fim Layout para SM-->

            <!--Coluna Esquerda-->


            <div class="col-md-2 d-none d-md-block" style="padding: 0;">
                <div class="bg-white p-2 mr-1 pt-4" style="border-radius: 7px;">
                    <div id="conteudo-esquerda">
                        <div>
                            
                                <img class=" center" src="/Front_end/foto-perfil.png" alt="">
                        
                            <p class="mt-2 mb-1 info-nome">Eu Odeio Acordar Cedo</p>
                            <div class="campos">
                                <div class=" mb-2">
                                    <span><img src="/Front_end/icons/participar.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">participar</p>
                                    </a> <br>
                                </div>
                            </div>
                                    
                                    <span><img src="/Front_end/icons/forum.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">fórum</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/enquetes.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">enquetes</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/eventos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">eventos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/membros.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">membros</p>
                                    </a> <br>
                                
                            
                           
                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col bg-transparent mr-1 mt-2">
                <div class="bg-white p-2  areas">
                    <h3 style="font-weight: 400;">Novo tópico</h3>
                    <div class="p-1" id="mini-nav">
                        <span><a href="">Início ></a></span> 
                        <span><a href=""> Comunidades > </a></span> 
                        <span><a href=""> Eu Odeio Acordar Cedo </a></span> 
                        <span style="color: gray;">> Fórum</span>
                        <span style="color: gray;">> Novo tópico</span>
                    </div>

                    <div class="no-margin social-info2 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Comunidade:</td>
                                <td class="size9"> Eu Odeio Acordar Cedo
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="no-margin social-info1 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Autor:</td>
                                <td class="size9"> Thiago André
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="no-margin social-info2 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Assunto:</td>
                                <td class="size9"> <input type="text">
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="no-margin social-info1 py-2">
                        <table class="ml-4">
                            <tr class="ml-4">
                                <td class="pr-3 texto-info-comunidade" style="vertical-align: top;">Mensagem:</td>
                                <td class="size9"> <textarea name="" id="" cols="70" rows="10"></textarea>
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="clearfix mt-1" style="border-top: 1px solid rgba(128, 128, 128, 0.144);">
                        <div style="float: left;">
                            <button class="btn btn-sm botao mt-2">
                                <a class="texto-botao">enviar</a>
                            </button>
                        </div>
                        <div style="float: left;" class="ml-3">
                            <button class="btn btn-sm botao mt-2">
                                <a href="/comunidade_page" class="texto-botao">cancelar</a>
                            </button>
                        </div>
                    </div>
                    
                </div>

            </div>

            <!--Fim Centro-->

            


        </div>
    </div>