<!--Coluna Esquerda-->


<div class="col-md-2 d-none d-md-block" style="padding: 0;">
                <div class="bg-white p-2 mr-1 pt-4" style="border-radius: 7px;">
                    <div id="conteudo-esquerda" class="ml-1">
                        <div>
                            <img class="ml-2" src="/uploads/<?= $this->view->info_usuario['image'] ?>" width="80%" alt="">
                            <p class="mt-2 mb-1 info-nome"><?= $this->view->info_usuario['nome'] ?></p>
                            <div style="border-top:1px solid #b7e8fa">
                                <div class="my-2">
                                <span><img src="/Front_end/icons/perfil.png" alt=""></span>
                                    <?php if($this->view->seguindo['num'] == 0){ ?>
                                        <a href="/acao?acao=seguir&id_usuario=<?= $this->view->info_usuario['id'] ?>">
                                        <p class="no-margin texto-info">adicionar amigo</p>
                                    </a>
                                   <?php   } else{ ?>
                                    <a href="/acao?acao=deixar_de_seguir&id_usuario=<?= $this->view->info_usuario['id'] ?>">
                                        <p class="no-margin texto-info">remover amigo</p>
                                    </a>
                                  <?php   } ?>
                                     
                                    
                                </div>
                            </div>
                            <div class="campos">
                                <div class="my-2">
                                    <span><img src="/Front_end/icons/perfil.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">perfil</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                    <a href="/recados?id=<?= $this->view->info_usuario['id']?>">
                                        <p class="no-margin texto-info">recados</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/fotos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">fotos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/videos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">vídeos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/depoimentos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">depoimentos</p>
                                    </a> <br>
                                </div>
                            </div>
                            
                           
                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--Fim Coluna Esquerda-->