<div class="container-fluid">

        <div class="row h-100">

            <!--Layout SM -->
            <div id="sm-container" class="col d-lg-none">
                <div class="bg-white container mt-3 areas">
                    <img src="\public\img\logo2.png" class="center pt-2"  alt="">
                    <p class="my-2" style="text-align:center">Acesse o  <strong>orkut.epizy</strong> com sua conta</p>
                     
                <div>
                    <form action="/autenticar" method="post">
                        
                    <img src="App\Views\index\" class="center pt-2"  alt="">
                                <input name="email_auth" type="email" class="form-control mb-2" placeholder="e-mail" name="email">
                            
                                <input name="senha_auth" type="password" class="form-control mb-2" placeholder="senha" name="senha">
                            
                                <button type="submit" class="btn btn-color mb-4 btn-block">Entrar </button>
                        
                    </form>
                </div>
                
                <!--Fim Login-->
                
                <h4 class="my-4"> Ainda não possui cadastro?</h4>

                
                <div class="mb-3 pb-1">
                <?php require("cadastro_codigo.php") ?>
                </div>
                </div>
                

            </div>
            <!--Layout SM -->

            <!--Coluna Esquerda-->
            <div class="col-6 d-none d-lg-block" id="coluna-esquerda">
                <div id="conteudo">
                    <img src="/public/img/logo-orkut.png" width="100%" alt="">
                </div>

               <div id="topicos">
                <div style="height: 35px;"></div>
                <p class="texto-esquerda">
                    <span><i class="fas fa-globe fa-2x mr-3"></i></span>
                    <strong>Conecta-se</strong> aos seus amigos e familiares
                </p>
                <p class="texto-esquerda mt-5">
                    <span><i class="fas fa-handshake fa-2x mr-3"></i></span>
                    <strong>Conheça</strong> novas pessoas através das comunidades
                </p>
                <p class="texto-esquerda mt-5">
                    <span><i class="fas fa-share fa-2x mr-3"></i></span>
                    <strong>Compartilhe</strong> seus vídeos, fotos e paixões em um só lugar
                </p>
               </div>
            </div>
            <!--Fim Coluna Esquerda-->

            <!--Coluna Direita-->
            <div class="col-6 d-none d-lg-block" id="coluna-direita">
                <!--Login-->
                <div>
                    <form action="/autenticar" method="post">
                        <div class="row mt-3">
                            <div class="col-md-5">
                                <input name="email_auth" type="email" class="form-control" placeholder="e-mail" name="email">
                            </div>
                            <div class="col-md-5">
                                <input name="senha_auth" type="password" class="form-control" placeholder="senha" name="senha">
                            </div>
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary">Entrar </button>
                            </div>
                        </div>
                        <?php if($this->view->login == 'erro'){ ?>
                            <span class="text text-danger size9">E-mail e/ou senha inválido(s)</span>
                        <?php  } ?>
                        
                    </form>
                </div>
                
                <!--Fim Login-->

                
                <h2 class="mt-5 ml-4">Ainda não possui cadastro no Orkut?</h2>

                <?php require("cadastro_codigo.php") ?>


            </div>
            <!--Fim Coluna Direita-->


        </div>
    </div>
    