<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

        <?php require('App\Views\componentes\barra_esquerda.phtml'); ?>

            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1">
                <div class="bg-white p-2" id="info-gerais">

                    <h3>Amigos</h3>
                    <div class="p-1 mb-1">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> <span
                            style="color: gray; font-size: 0.9em;">> Amigos</span>
                    </div>
                    <div class="clearfix border-bottom">
                        <div id="explorar1" style="padding: 1px 5px; float:left" class="mt-2">
                            <a href="" class="no-margin" style="font-size:0.8em">todos os amigos (<?= count($this->view->friends) ?>)</a>
                        </div>
                       
                    </div>
                    <?php 
                        foreach($this->view->friends as $friends){
                            ?>
                                <div class="p-2 mt-1" style="background: #f0f7ff;">
                        <img src="/uploads/<?= $friends['image'] ?>" width="80px" alt="">
                        <a href="/perfil?id=<?= $friends['id'] ?>">
                        <p style="display: inline;" class="no-margin"><?=
                        $friends['nome'] ?>
                         </p>
                        </a>
                    </div>
                        <?php  } 
                    ?>

                    


                </div>

            </div>

            <!--Fim Centro-->

            <!--Começo Coluna Direita-->
            <div class="col d-none d-md-block bg-transparent" style="padding: 0;">


                <div class="bg-white p-2 mt-2" id="grupos" style="border-radius: 10px;">
                    <h4>grupos de amigos <span>(0)</span></h4>

                    <div class="campos mt-2" style="border-bottom: 1px solid white;">
                        <a style="font-size:0.9em" href="">escola</a>
                        <a style="font-size:0.9em" href="">família</a>
                        <a style="font-size:0.9em" href="">melhores amigos(as)</a>
                        <a style="font-size:0.9em" href="">trabalho</a>

                    </div>
                </div>

            </div>

            <div class="col-md px-3 d-md-none  bg-transparent" style="padding: 0;">


                <div class="bg-white p-2 mt-2" id="grupos" style="border-radius: 10px;">
                    <h4>grupos de amigos <span>(0)</span></h4>

                    <div class="campos mt-2" style="border-bottom: 1px solid white;">
                        <a style="font-size:0.9em" href="">escola</a>
                        <a style="font-size:0.9em" href="">família</a>
                        <a style="font-size:0.9em" href="">melhores amigos(as)</a>
                        <a style="font-size:0.9em" href="">trabalho</a>

                    </div>
                </div>

            </div>


            <!--Fim Coluna Direita-->


        </div>
    </div>