

<script>
$(document).ready(function(){
  $(".exportt").click(function(){
    var imageData = $('.image-editor').cropit('export',{
             type: 'image/jpeg',
         quality: 0.33,
            });
            $("#hidden_base64").val(imageData);
  });
});

function criarCookie(value) { 
    var data = new Date();
    data.setTime(data.getTime() + 60000);
    document.cookie = "primeiroCookie="+value+"; expires="+data.toUTCString()+"; path=/";
    return "sucesso";
} 

</script>

<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Layout para SM-->
            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1 d-md-none">
                <div class="bg-white p-2" id="info-gerais">

                    <h3>Comunidades</h3>
                    <div class="p-1 mb-2">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> <span style="color: gray; font-size: 0.9em;">> Comunidades</span>
                    </div>
                    <p class="size9">Compartilhe suas paixões. Conheça pessoas que têm interesses em comum. Troque idéias. Planeje eventos...</p>
                    <p class="size9">Você pode pesquisar comunidades ou criar sua própria comunidade.</p>

                </div>

                <div class="bg-white p-2 mt-2" id="info-gerais">

                    <h4>Suas comunidades(<?= count($this->view->comunidade) ?>)</h4>
                    <table style="width: 100%; margin: 0 auto;">
                        <thead>
                            <td style="padding: 10px;" class="td-left">
                                <p class="no-margin tabela-header">nome</p>
                            </td>

                        </thead>


                        <?php 
                            foreach($this->view->comunidade as $key=>$comunidade){
                                ?>
                                    <tr class="
                                    <?php if($key%2==0){
                                        echo 'bg-listrado-1';
                                    } else echo 'bg-listrado-2';
                                    ?>
                                    ">
                            <td class="td-left py-1"><a href="/comunidade_page"><?= $comunidade['nome'] ?></a></td>
                        </tr>
                            <?php  }
                        ?>

                        

                       

                    </table>

                </div>

            </div>

            <!--Fim Centro-->

            <!--Começo Coluna Direita-->
            <div class="col-md p-2 d-md-none " style="padding: 0;">

                <div class="bg-white p-2 mt-2" style="border-radius: 10px;">
                    <h4>todas as comunidades<span>(0)</span></h4>

                    <div class="campos mt-2" style="border-bottom: 1px solid white;">

                        <p class="no-margin mb-1" style="font-size:0.9em">pesquisar por nome:</p>
                        <input type="text" style="line-height: normal; width: 100%;">
                        <div class="row mt-2">
                            <div class="col-4">
                                <button style="display: block;" class="btn btn-sm botao mt-1">
                                    <a href="/pesquisa_comunidade" class="texto-botao">pesquisar</a>
                                </button>
                            </div>
                            <div class="col-8">
                                <button style="display: block;" class="btn btn-sm botao mt-1">
                                    <a class="texto-botao">criar comunidade</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!--Fim Coluna Direita-->
            <!--Fim Layout para SM-->

            <!--Coluna Esquerda-->
            <div class="col-md-2 d-none d-md-block" style="padding: 0;">
                <div class="bg-white p-2 mr-1" style="border-radius: 7px;">
                    <div id="conteudo-esquerda" class="px-1">
                        <div>
                            <img class="fix-size-img" src="/uploads/<?= $this->view->info_usuario['image'] ?>" alt="">
                            <div style="text-align:center">
                            <input id="add_foto_button" type="button" 
                            value="<?php if($this->view->info_usuario['image'] == "foto-default.png") { 
                                echo "adicionar foto";} else{
                                echo "editar foto";} ?>" 
                            class="no-margin texto-info" data-toggle="modal" data-target="#exampleModal" ></input> 
                           
                        </div>
                          
                        <!-- Button trigger modal -->
                        
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Editar fotos</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                        <div class="image-editor">
                                            <input type="file" class="cropit-image-input form-control-file mb-3">
                                            <div style="max-width: none;" class="cropit-preview img-size"></div>
                                            <div style="max-width: none;" class="image-size-label">
                                                Resize image
                                            </div>
                                            <input type="range" class="cropit-image-zoom-input">
                                            </div>
                                    
                                </div>
                                <div class="modal-footer">

                                <form action="/addImage" method="post">
                                      <input style="display:none" name="base64" id="hidden_base64" type="text">
                                      <button style="float:left" type="submit" class="btn btn-sm botao exportt">
                                      <a class="texto-botao">recortar</a>
                                    </button>
                                </form>

                                <button type="button" class="btn btn-sm botao">
                                    <a href="editar_perfil" class="texto-botao">fechar</a>
                                </button>
                                    
                                </div>
                                </div>
                            </div>

                            </div>
                            </div>
                            <p class="mt-2 mb-1 info-nome">Thiago André</p>
                            <div class="campos">
                                <div class="mt-2 mb-2">
                                    <span><img src="/Front_end/icons/perfil.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">perfil</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">recados</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/fotos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">fotos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/videos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">vídeos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/depoimentos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">depoimentos</p>
                                    </a> <br>
                            </div>
                            <div class="campos">
                                <div class="mb-2">
                                    <h4>Apps</h4>
                                    <span><img src="/Front_end/icons/apps.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">adicionar apps</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div class="campos pb-2" style="border-bottom: 1px solid white;">
                                <div class="mt-2">
                                    <span><img src="/Front_end/icons/lista.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">listas</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/atualizaçoes.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">atualizações</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/configuracao.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">configurações</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col-md bg-transparent mr-1 d-none d-md-block">
                <div class="bg-white p-2" id="info-gerais">
                                    
                    <h3>Editar Perfil</h3>
                    <div class="p-1 mb-2">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> >
                        <span><a style="font-size: 0.9em;" href="">Meu Perfil</a></span> 
                        <span style="color: gray; font-size: 0.9em;">> Editar Perfil</span>

                    </div>
                    <div style="border-bottom: 1px solid rgba(128, 128, 128, 0.253);"></div>
                    <table style="width:100%;">
                                <form action="/acao?acao=save" method="post" enctype="multipart/form-data">
                                <tr class="bg-listrado-1">
                                    <td class="pr-3 py-2 texto-info-comunidade" style="vertical-align: top;padding-left:25%">nome:</td>
                                    <td class="size9 py-2"> <input name="nome" type="text">
                                    </td>   
                                </tr>
                                <tr class="bg-listrado-2">
                                    <td class="pr-3 py-2 texto-info-comunidade" style="vertical-align: top;padding-left:25%">sobrenome:</td>
                                    <td class="size9 py-2"> <input name="sobrenome" type="text">
                                    </td>   
                                </tr>
                                <tr class="bg-listrado-1">
                                    <td class="pr-3 py-2 texto-info-comunidade" style="vertical-align: top;padding-left:25%">data:</td>
                                    <td class="size9 py-2"> 
                                    <?php require('App\Views\componentes\form_data.phtml') ?>
                                    </td>   
                                </tr>
                                
                            </table>

                            <div class="pt-1">
                                <button class="btn btn-sm botao" style="line-height:12px">
                                <a type="submit" class="texto-botao">atualizar</a>
                            </button>
                           
                            </div>
                            </form>
                </div>

            </div>

            <!--Fim Centro-->


        </div>
    </div>
 
  