<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Coluna Esquerda-->


            <div class="col-md-2 d-none d-md-block" style="padding: 0;">
                <div class="bg-white p-2 mr-1 pt-4" style="border-radius: 7px;">
                    <div id="conteudo-esquerda" class="ml-1">
                        <div>
                            <img class="ml-2" src="/Front_end/foto-perfil.png" width="80%" alt="">
                            <p class="mt-2 mb-1 info-nome">Thiago André</p>
                            <div class="campos">
                                <div class="mt-2 mb-2">
                                    <span><img src="/Front_end/icons/perfil.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">perfil</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">recados</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/fotos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">fotos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/videos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">vídeos</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/depoimentos.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">depoimentos</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div class="campos">
                                <div class="mb-2">
                                    <h4>Apps</h4>
                                    <span><img src="/Front_end/icons/apps.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">adicionar apps</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div class="campos pb-2" style="border-bottom: 1px solid white;">
                                <div class="mt-2">
                                    <span><img src="/Front_end/icons/lista.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">listas</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/atualizaçoes.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">atualizações</p>
                                    </a> <br>
                                    <span><img src="/Front_end/icons/configuracao.png" alt=""></span>
                                    <a href="">
                                        <p class="no-margin texto-info">configurações</p>
                                    </a> <br>
                                </div>
                            </div>
                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col bg-transparent mr-1 mt-2">
                <div class="bg-white p-2  areas">

                    <!--Título e Nav-->
                    <h3 style="font-weight: 400;">Encontrar amigos</h3>
                    <div class="p-1" id="mini-nav">
                        <span><a href="">Início ></a></span>
                        <span style="color:gray"> Pesquisar</span>
                    </div>
                    <!--Fim Título e Nav-->

                    <!--sugestoes amigos-->

                    <p class="no-margin size9">Pesquisar amigos:</p>
                    <span><input type="text"></span>
                    <span>
                        <button class="btn btn-sm botao mb-1">
                            <a class="texto-botao">pesquisar</a>
                        </button>
                    </span>
                    <div class="clearfix mt-2" style="background: #f0f7ff;">

                        <div style="border-bottom:4px solid white ;" class="clearfix">

                            <div class="resposta">
                                <img class="img-resposta ml-2" src="/Front_end/foto-perfil.png" alt="">
                            </div>
                            <div style="float: left;" class="mt-3 pt-1">
                                <div class="ml-2" style="float: left;">
                                    <a class="" href="">Nicolle</a>

                                </div>

                            </div>
                        </div>

                        <div class="resposta">
                            <img class="img-resposta ml-2" src="/Front_end/foto-perfil.png" alt="">
                        </div>
                        <div style="float: left;" class="mt-3 pt-1">
                            <div class="ml-2" style="float: left;">
                                <a href="">Diego</a>
                            </div>

                        </div>

                    </div>

                    <!--Fim sugestoes amigos-->


                </div>

            </div>

            <!--Fim Centro-->




        </div>
    </div>