<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

            <!--Layout para SM-->
        <div class="col d-block d-md-none bg-transparent">

<div class="areas p-1">
    <div class="row">
        <div class="col-3 ">
            <img class="fix-size-img ml-1" src="/uploads/<?= $this->view->info_usuario['image'] ?>" class="mt-3" alt="">
        </div>
        <div class="col-9">
            <p class="info-nome"><?= $this->view->info_usuario['nome'] ?></p>
            <div class="clearfix">
                <div style="float: left;" class="mr-2 ml-1 size9">
                    <p class="no-margin size8 texto-menu">recados</p>
                    <img src="/Front_end/icons/recados.png" alt=""> <span class="size8">2</span>
                </div>
                <div style="float: left;" class="mr-2 size9">
                    <p class="no-margin texto-menu">fotos</p>
                    <img src="/Front_end/icons/fotos.png" alt=""> <span class="size8">2</span>
                </div>
                <div style="float: left;" class="mr-2 size9">
                    <p class="no-margin size8 texto-menu">vídeos</p>
                    <img src="/Front_end/icons/videos.png" alt=""> <span class="size8">2</span>
                </div>
                <div style="float: left;" class="mr-2 size9">
                    <p class="no-margin size8 texto-menu">fãs</p>
                    <img src="/Front_end/icons/fas.png" alt=""> <span class="size8">2</span>
                </div>
                <br><br>


                <div class="row pl-3">
                    <div class="menu-geral  size9">
                        <p class="no-margin texto-menu">confiável</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/confiavel.png" alt="">
                    </div>
                    <div class="menu-geral  size9">
                        <p class="no-margin texto-menu">legal</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/legal.png" alt="">
                    </div>
                    <div class="menu-geral  size9">
                        <p class="no-margin texto-menu">sexy</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/coracoes.png" alt="">
                    </div>


                </div>

            </div>
        </div>
        <div class="col-3 ">

        </div>
    </div>
</div>

<div class="col areas p-2 mt-2">
    <div id="social" class="mt-2">
        <p class="no-margin">social</p>
    </div>


    <div id="social-info">
        <div class="no-margin social-info1 py-2">
            <p class="no-margin">aniversário: <?= $this->view->info_usuario['data'] ?></p>
        </div>
        <div class="no-margin social-info2 py-2">
            <p class="no-margin">relacionamento: solteiro(a)</p>
        </div>
        <div class="no-margin social-info1 py-2">
            <p class="no-margin">país: Brasil</p>
        </div>
    </div>
</div>

<div class="col-md mt-2" style="padding: 0;">
    <div class="bg-white p-2" style="border-radius: 10px;">
        <h4>meus amigos <span> <a href="/amigos">(<?= $this->view->friends_number ?>)</a> </span></h4>
        <div class="row" style="margin:auto">
            <?php

            if (isset($this->view->friends3[0])) {
                foreach ($this->view->friends3 as $key => $friends) { ?>


                    <div class="col" style="background:#F0F0F0;border:3px solid white">
                        <img class="fix-size-img px-3 pt-1" src="uploads/<?= $this->view->friends[$key]['image'] ?>" alt="">
                        <p class="texto-perfil"><?= $this->view->friends[$key]['nome'] ?></p>
                    </div>

            <?php }
            }
            ?>
        </div>
    </div>

    <div class="bg-white p-2 my-2" style="border-radius: 10px;">
        <h4>minhas comunidades <span><a href="/comunidades">(<?= $this->view->comunidades_number ?>)</a></span></h4>
        <div class="row" style="margin:auto">
            <?php

            if (isset($this->view->comunidades3[0])) {
                foreach ($this->view->comunidades3 as $key => $comunidades) { ?>


                    <div class="col" style="background:#F0F0F0;border:3px solid white">
                        <img class="fix-size-img px-3 pt-1" src="uploads_comunidade/<?= $this->view->comunidades[$key]['imagem'] ?>" alt="">
                        <a href="/comunidade_page?id=<?= $comunidades['id'] ?>""><p class="texto-perfil"><?= $this->view->comunidades[$key]['nome'] ?></p></a>
                    </div>

            <?php }
            }
            ?>
        </div>
       

</div>

</div>
</div>

<!-- Fim Layout para SM-->

            <?php 
                if($_GET['id'] == $_SESSION['id']){
                    require('App/Views/componentes/barra_esquerda.phtml');
                } else {
                    require('App/Views/componentes/barra_esquerda_perfil_others.phtml');
                }
             ?>

            <!--Coluna Centro-->
            <div class="col-md-6 col-lg-7 bg-transparent mr-1 d-none d-md-block">
                <div class="bg-white p-2" id="info-gerais"> 
                    <h3 style="font-weight: 400;"><?= $this->view->info_usuario['nome'] ?></h3>
                    <div class="p-1">
                        <span><a href="">Início</a></span> <span style="color: gray;">> Meu perfil</span>
                    </div>


                    <div class="row mx-2 mt-2 p-1" id="frase-perfil">    
                        
                                <p id="p-frase" class="no-margin pt-1"><?php 
                                if($_GET['id'] == $_SESSION['id']){ ?>
                                    <div class="col-8">
                                <p id="p-frase" class="no-margin pt-1"><?php 
                                if($this->view->info_usuario['frase'] == null || $this->view->info_usuario['frase'] == ''){  
                                    echo 'Qual é a sua frase de perfil?';}  else{
                                     echo $this->view->info_usuario['frase']; }  
                                     ?>
                                </p>
                        </div>
                        <div class="col-4">
                        <button onclick=" setFrase()" style="height:30px; float:right" class="btn btn-sm botao">
                            <a  class="texto-botao">Editar</a>
                        </button>
                        </div>
                               <?php  } else{ ?>
                                    <div class="col-8">
                                    <p id="p-frase" class="no-margin pt-1"> <?php  
                                    if($this->view->info_usuario['frase'] != null || $this->view->info_usuario['frase'] != '')
                                    {
                                     echo $this->view->info_usuario['frase']; }  
                                     ?>
                                    </p>
                                    </div>
                               <?php } ?> 

                                
                                </p>
                        
                    </div>

                   

                    <div class="row ml-2 mt-3 campos py-2 mr-2">
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">recados</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/recados.png" width="25%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">fotos</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/fotos.png" width="50%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">videos</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/videos.png" width="40%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">fas</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/fas.png" width="52%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">mensagens</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/mensagens.png" width="25%" alt="">0
                        </div>
                    </div>
                    <div class="row ml-2 mt-3 mb-3 mr-2 pb-2" style="border-bottom:1px solid #b7e8fa">
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">confiável</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/confiavel.png" alt="">
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">legal</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/legal.png" alt="">
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin texto-menu">sexy</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/coracoes.png" alt="">
                        </div>

                    </div>


                    <div id="social" class="mt-2">
                        <p class="no-margin">social</p>
                    </div>


                    <div id="social-info">
                        <div class="no-margin social-info1 py-2">
                            <p class="no-margin">aniversário: <?= $this->view->info_usuario['data']; ?> </p>
                        </div>
                       
                        <div class="no-margin social-info2 py-2">
                            <p class="no-margin">país: Brasil</p>
                        </div>
                    </div>


                </div>


            </div>

            <!--Fim Centro-->

            <?php require_once('App/Views/componentes/barra_direita.phtml'); ?>


        </div>
    </div>

    


    <script>
        
        function setFrase(){
            $('#frase-perfil').html('<div><form action="/frase" method="post"> <input type="text" name="frase" class="mb-1" style="width:100%; height:25px">  <button type="submit" style="height:30px;" class="btn btn-sm botao"><a class="texto-botao">atualizar</a></button><button style="height:30px;" class="btn btn-sm botao"><a href="/perfil" class="texto-botao">cancelar</a></button> </form></div>');
        }
        
    </script>
                  