<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">

           <!--Coluna Esquerda-->


           <div class="col-md-2 d-none d-md-block" style="padding: 0;">
            <div class="bg-white p-2 mr-1 pt-4" style="border-radius: 7px;">
                <div id="conteudo-esquerda" class="ml-1">
                    <div>
                        <img class="ml-2" src="/Front_end/foto-perfil.png" width="80%" alt="">
                        <p class="mt-2 mb-1 info-nome">Thiago André</p>
                        <div class="campos">
                            <div class="mt-2 mb-2">
                                <span><img src="/Front_end/icons/perfil.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">perfil</p>
                                </a> <br>
                                <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">recados</p>
                                </a> <br>
                                <span><img src="/Front_end/icons/fotos.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">fotos</p>
                                </a> <br>
                                <span><img src="/Front_end/icons/videos.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">vídeos</p>
                                </a> <br>
                                <span><img src="/Front_end/icons/depoimentos.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">depoimentos</p>
                                </a> <br>
                            </div>
                        </div>
                        <div class="campos">
                            <div class="mb-2">
                                <h4>Apps</h4>
                                <span><img src="/Front_end/icons/apps.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">adicionar apps</p>
                                </a> <br>
                            </div>
                        </div>
                        <div class="campos pb-2" style="border-bottom: 1px solid white;">
                            <div class="mt-2">
                                <span><img src="/Front_end/icons/lista.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">listas</p>
                                </a> <br>
                                <span><img src="/Front_end/icons/atualizaçoes.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">atualizações</p>
                                </a> <br>
                                <span><img src="/Front_end/icons/configuracao.png" alt=""></span>
                                <a href="">
                                    <p class="no-margin texto-info">configurações</p>
                                </a> <br>
                            </div>
                        </div>
                        <div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1">
                <div class="bg-white p-2" id="info-gerais">

                    <h3 style="font-size:1.5em">Resultado de pesquisa para odeio acordar cedo</h3>
                    <div class="p-1 mb-2">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> <span
                            style="color: gray; font-size: 0.9em;">> Pesquisar</span>
                    </div>
                    <div id="explorar" style="padding: 2px 5px;" class="mt-2">
                        <p class="no-margin">comunidades</p>
                    </div>
                    <div class="p-2 mt-3" style="background: #f0f7ff;">
                        <img src="/Front_end/foto-perfil.png" width="80px" alt="">
                        <a class="no-margin" href="">Eu odeio Acordar Cedo </a>
                    </div>

                    <div class="p-2 mt-3" style="background: #f0f7ff;">
                        <img src="/Front_end/foto-perfil.png" width="80px" alt="">
                        <a class="no-margin" href="">Eu odeio Acordar Cedo </a>
                    </div>
                </div>

            </div>

            <!--Fim Centro-->



        </div>
    </div>