<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">
        <?php 
        require("App\Views\componentes\barra_esquerda.phtml");
        ?>
            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1 ">
                <div class="bg-white p-2 pb-4" id="info-gerais">

                    <h3 style="font-size:1.5em">Resultado de pesquisa para</h3>
                    <div class="p-1 mb-2">
                        <span><a style="font-size: 0.9em;" href="">Início</a></span> <span
                            style="color: gray; font-size: 0.9em;">> Pesquisar</span>
                    </div>

                    <div class="clearfix border-bottom">
                        <div id="<?= $this->view->exp == 1 ? "explorar1" : "explorar2" ?>" style="padding: 1px 5px; float:left" class="mt-2">
                            <a href="/pesquisar?exp=1&q=<?= $_GET['q'] ?>" class="no-margin">usuários</a>
                        </div>
                        <div id="<?= $this->view->exp == 1 ? "explorar2" : "explorar1" ?>" style="margin-left:10px; padding: 1px 5px; float:left" class="mt-2">
                            <a href="/pesquisar?exp=2&q=<?= $_GET['q'] ?>" class="no-margin">comunidades</a>
                        </div>
                    </div>

                    <div id="pesquisa_novamente">
                        <p class="my-2 size9">pesquisar novamente:</p>
                        <form action="/pesquisar" class="clearfix">
                            <input style="display:none" name="exp" value="<?= $this->view->exp == 1 ? "1" : "2" ?>" type="text">
                            <input name = "q" type="text" style="line-height:5px">
                            <button style="line-height:15px"; class="btn btn-sm botao ml-2 mb-1 px-2" >
                            <a  class="texto-botao">pesquisar</a>
                        </button>
                        </form>
                        <div style="position:absolute; right:0px" class="pr-4">
                            <p class="size8 no-margin">< anterior | <a href="">próxima</a> ></p>
                        </div>
                    </div>

                    <div>

                    
                    <?php 
                    foreach($this->view->infos as $usuarios){ ?>

                     <div class="p-2 mt-3" style="background: #f0f7ff;">
                        <img src="/Front_end/foto-perfil.png" width="80px" alt="">
                        <a class="no-margin" href="/perfil?id=<?=$usuarios['id']?>"><?= $usuarios['nome'] ?> </a>
                    </div>

                   <?php }
                   
                   ?>

                    
                   
                        
                    

                    
                </div>
                
               

            </div>

            <!--Fim Centro-->



        </div>
    </div>