<div class="container mt-2" style="border-radius: 5%; ">

        <div class="row h-100">
            
            <?php require('App\Views\componentes\barra_esquerda.phtml'); ?>

            <!--Coluna Centro-->
            <div class="col-md-7 bg-transparent mr-1">
                <div class="bg-white p-2" id="info-gerais">
                    <h3 style="font-weight: 400;">Bem-vindo(a), <?php echo $this->view->info_usuario['nome'];?> </h3>
                    <div class="row ml-2 mt-3">
                        <div class="menu-geral">
                            <p class="no-margin">recados</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/recados.png" width="25%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin">fotos</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/fotos.png" width="50%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin">videos</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/videos.png" width="40%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin">fas</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/fas.png" width="52%" alt="">0
                        </div>
                        <div class="menu-geral">
                            <p class="no-margin">mensagens</p>
                            <img class="no-margin mr-1" src="/Front_end/icons/mensagens.png" width="25%" alt="">0
                        </div> 
                    </div>
                    <div class="mt-4 mr-3 ml-1">
                            <h4>Visualizações de seu perfil:</h4>
                            <p class="no-margin" style="font-size: 0.9em;">
                                Desde Jul. 2017: 0</p>
                        </div>
                        <div class="mt-3 ml-1">
                            <h4>Sorte de hoje:</h4>
                            <p class="no-margin" style="font-size: 0.9em;"><?php echo $this->view->sorte['sorte_de_hoje'];?></p>
                        </div>

                </div>
        
                
                <div id="explorar1" class="mt-2">
                    <p class="no-margin">explorar</p>
                </div>

        <div class="p-4 bg-white">
        <div class="owl-carousel owl-theme">
   
    
        <?php foreach($this->view->info_usuarios as $id_usuarios => $usuarios) { ?>
            <div class="item col px-3 pt-3 pb-5" style="background:#F0F0F0">
    <div style="height:90px">
    <img class="fix-size-img" src="/uploads/<?= $usuarios['image'] ?>" alt="">
   <a href="/perfil?id=<?=$usuarios['id']?>"> <p class="texto-perfil"> <?= $usuarios['nome'] ?></p></a>
   <a href="" class="btn-adicionar">Adicionar</a>
    </div>
    </div>
			<?php } ?> 

        
        









</div>
        </div>

            </div>

            <!--Fim Centro-->

           <?php require("App\Views\componentes\barra_direita.phtml") ?>


        </div>
    </div>