<div class="container mt-2 " style="border-radius: 5%; ">

        <div class="row h-100">
            
            <!--Coluna Esquerda-->
            <div class="col-2 mr-1  pt-4 bg-white p-3" style="border-radius: 7px;">

                    <div id="conteudo-esquerda" >
                        <div>
                            <img src="/Front_end/foto-perfil.png" width="80%" alt="">
                            <p id="info-nome" class="mt-2 mb-1">Fulano Beltrano</p>
                             <div class="campos">
                                <div class="mt-2 mb-2">
                                    <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                    <p class="no-margin texto-info">perfil</p> <br>
                                    <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                    <p class="no-margin texto-info">recados</p>  <br>
                                    <span><img src="/Front_end/icons/fotos.png" alt=""></span>
                                    <p class="no-margin texto-info">fotos</p> <br>
                                    <span><img src="/Front_end/icons/videos.png" alt=""></span>
                                    <p class="no-margin texto-info">vídeos</p>  <br>
                                    <span><img src="/Front_end/icons/mensagens.png" alt=""></span>
                                    <p class="no-margin texto-info">depoimentos</p>  <br>
                                </div>
                            </div>
                            <div class="campos">
                                <div class="mb-2">
                                    <h4>Apps</h4>
                                <span><img src="/Front_end/icons/recados.png" alt=""></span>
                                    <p class="no-margin texto-info">adicionar apps</p>  <br>
                                </div>
                            </div>
                            <div class="campos pb-2">
                                <div class="mt-2">
                                    <span><img src="/Front_end/icons/mensagens.png" alt=""></span>
                                    <p class="no-margin texto-info">listas</p>  <br>
                                    <span><img src="/Front_end/icons/mensagens.png" alt=""></span>
                                    <p class="no-margin texto-info">atualizações</p>  <br>
                                    <span><img src="/Front_end/icons/mensagens.png" alt=""></span>
                                    <p class="no-margin texto-info">configurações</p>  <br>
                                </div>
                            </div>
                        <div>

                            </div>
                        </div>
                    </div>
            </div>

            <!--Fim Coluna Esquerda-->

            <!--Coluna Centro-->
            <div class="col-6 bg-transparent mr-1">
                <div class="bg-white p-2" id="info-gerais">
                    <h2 style="font-weight: 400;">Bem-vindo(a), Fulano</h2>
                   <div class="row ml-2 mt-3">
                    <div class="menu-geral">
                        <p class="no-margin">recados</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/recados.png" width="25%" alt="">1
                    </div>
                    <div class="menu-geral">
                        <p class="no-margin">fotos</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/fotos.png" width="50%" alt="">1
                    </div>
                    <div class="menu-geral">
                        <p class="no-margin">videos</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/videos.png" width="40%" alt="">1
                    </div>
                    <div class="menu-geral">
                        <p class="no-margin">fas</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/fas.png" width="52%" alt="">1
                    </div>
                    <div class="menu-geral">
                        <p class="no-margin">mensagens</p>
                        <img class="no-margin mr-1" src="/Front_end/icons/mensagens.png" width="25%" alt="">1
                    </div>
                    <div class="mt-4 mr-3">
                        <h4>Visualizações de seu perfil:</h4>
                         <p class="no-margin" style="font-size: 0.9em;">
                            Desde Jul. 2017: 0, Semana passada: 0, Ontem: 0</p>
                    </div>
                    <div class="mt-3">
                        <h4>Seus visitantes recentes:</h4> 
                        <p class="no-margin" style="font-size: 0.9em;">nenhum</p>
                    </div>
                    <div class="mt-3">
                        <h4>Sorte de hoje:</h4> 
                        <p  class="no-margin" style="font-size: 0.9em;">Uma imaginação bem canalizada é fonte de grandes proezas.</p>
                    </div>
                   </div>

                </div>
                <div class="mt-4 bg-white radius p-2">
                    <p style="font-size: 0.9em; font-weight: 500;">sugestões de amigos do orkut</p>
                    
                    <div class="clearfix" id="sugestao"> 
                        <div>
                            <button class="btn btn-primary menu-geral"></button>
                        </div>
                        <div class="menu-geral" style=" max-width: 90px">
                            <div class="pb-1" style="background: #f0f0f0;">
                                <img src="/Front_end/foto-perfil.png" class="img pt-2 pl-2 pr-2" alt="">
                            <a href=""><p class="no-margin mb-2 texto-perfil">Fulano</p></a>
                            </div>
                            <a href=""><p class="no-margin texto-perfil">adicionar</p></a>    
                        </div>

                        <div class="menu-geral" style=" max-width: 90px">
                            <div class="pb-1" style="background: #f0f0f0;">
                                <img src="/Front_end/foto-perfil.png" class="img pt-2 pl-2 pr-2" alt="">
                            <a href=""><p class="no-margin mb-2 texto-perfil">Fulano</p></a>
                            </div>
                            <a href=""><p class="no-margin texto-perfil">adicionar</p></a>    
                        </div>

                       <div class="menu-geral" style=" max-width: 90px">
                            <div class="pb-1" style="background: #f0f0f0;">
                                <img src="/Front_end/foto-perfil.png" class="img pt-2 pl-2 pr-2" alt="">
                            <a href=""><p class="no-margin mb-2 texto-perfil">Fulano</p></a>
                            </div>
                            <a href=""><p class="no-margin texto-perfil">adicionar</p></a>    
                        </div>

                        <div class="menu-geral" style=" max-width: 90px">
                            <div class="pb-1" style="background: #f0f0f0;">
                                <img src="/Front_end/foto-perfil.png" class="img pt-2 pl-2 pr-2" alt="">
                            <a href=""><p class="no-margin mb-2 texto-perfil">Fulano</p></a>
                            </div>
                            <a href=""><p class="no-margin texto-perfil">adicionar</p></a>    
                        </div>

                        <div>
                            <button class="btn btn-primary" style="float: right;"></button>
                        </div>
                   </div>
                </div>

                <div id="explorar" class="mt-2">
                    <p class="no-margin">explorar</p>
                </div>
                
            </div>

            <!--Fim Centro-->

            <!--Começo Coluna Direita-->
            <div class="col-3 bg-transparent" style="padding: 0;">
                <div class="bg-white p-2" style="border-radius: 10px;">
                    <h4>meus amigos <span>(0)</span></h4>
                    <div class="mt-1 p-1" style="background: #eef7ff;">
                        <p class="no-margin" style="font-size: 0.8em;">você ainda não adicionou nenhum amigo</p>
                    </div>
                    <div class="campos mt-2" style="border-bottom: 1px solid white;">
                        <div class="mb-1"></div>
                        <button class="btn btn-sm botao">
                            <a class="texto-botao">Adicionar amigos</a>
                        </button>
                    </div>
                </div>
                
            </div>
            <!--Fim Coluna Direita-->


        </div>
    </div>