<html lang="pt-br">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!--CSS-->
  <link rel="stylesheet" type="text/css" href="estilos/estilo_geral1.css">
  <link rel="stylesheet" type="text/css" href="estilos/layout1_style.css">

  <link rel="icon" href="https://www.orkut.br.com/assets/img/favicon.png">

  <!--Font Awesome-->
  <script src="https://kit.fontawesome.com/833591d3ed.js" crossorigin="anonymous"></script>

  <!--Jquery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <script src="/jquery.cropit.js"></script>

  <title>Início Orkut</title>
</head>

<body>
  <?= $this->content() ?>
</body>




</html>