<html>
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!--CSS-->
    <link rel="stylesheet" type="text/css" href="style.css">

    <!--Font Awesome-->
    <script src="https://kit.fontawesome.com/833591d3ed.js" crossorigin="anonymous"></script>
  
    <title>Início Orkut</title>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="/jquery.cropit.js"></script>

    <style>
        body{
            background: white;
        }
        #sm-container{
          background: #e458a2;
        }
        .center {
          display: block;
          margin-left: auto;
          margin-right: auto; 
        }
        .btn-color{
          background-color: #e7e7e7;
        }
        .texto-esquerda{
          color: white;
          font-size: 1.3em;
      }


      </style>
		

	</head>

	<body>
		<?= $this->content() ?>
	</body>


  
 
</html>