<html>
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!--CSS-->
    <link rel="stylesheet" type="text/css" href="/public/css/style.css">

    <!--Font Awesome-->
    <script src="https://kit.fontawesome.com/833591d3ed.js" crossorigin="anonymous"></script>

    <title>Início Orkut</title>

		

	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>