<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <!--Font Awesome-->
      <!--CSS-->
   <link rel="stylesheet" type="text/css" href="/public/css/style.css">
        <script src="https://kit.fontawesome.com/833591d3ed.js" crossorigin="anonymous"></script>

        <style>
            #nav{
                background: url('/Front_end/barra.png') repeat-x;
                
            }
            .logo {
                width: 79px;
                height: 32px;
                background: url('/Front_end/logo.png') -158px 0;
            }
            .nav{
                width: 67%;
                margin: 0 auto;
            }

                    nav a {
                color: white;
                font-size: 0.9em;
                }
            body{
                background: #d9e6f7;
            }
            #conteudo-botao{
                height: 70%;
                width: 100%;
                background: white;
                border-radius: 5%;
            }
            #foto-perfil{
                width: 30%;
                margin: 0 auto;
            }
            #nome{
                height: 10%;
                border-bottom: ;
                border-top: 1px solid #b7e8fa ;
            }
        </style>
</head>
<body>
    <div id="container">

        <nav class="navbar navbar-expand-sm py-0" id="nav">
            <div class="container">
            <!--Logo-->
            <a href="#" class="navbar-left"><img src="/Front_end/logo.png"></a>

            <div class="d-none d-md-block">
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <a href="" class="nav-link">Início</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Página de recados</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Amigos</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Comunidades</a>
                    </li>
                </ul>
            </div>
            
            
            <!--Menu botões para SM-->

            <button class="navbar-toggler ml-auto">
                <span><i class="fas fa-search" style="color:#fff; font-size:28px;"></i></span>
            </button>

            <button onclick="myFunction()" class="navbar-toggler" data-toggle="collapse" data-target="#nav-target2">
                <span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span>
            </button>
    
            <!--Navegação-->
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="" class="nav-link d-none d-lg-block">fulano@gmail.com</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Sair</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Pesquisar no orkut</a>
                    </li>
                </ul>
            </div>

            

            <!--<div id="nav-target2" class="collapse navbar-collapse">
                <div id="conteudo-botao">
                    <div id="foto-perfil">
                        <img src="/Front_end/foto-perfil.png" width="100%" alt="">
                    </div>
                    <div id="nome">
                        <p style="text-align: center;">Thiago André</p>
                    </div>
                </div>
            </div>-->
        </div>
        
      
    </div>

    <body>
		<?= $this->content() ?>
	</body>

    <script>
        var x = document.getElementById("nav-target2");
        x.style.display = "none";
        function myFunction() {
          var x = document.getElementById("nav-target2");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }
        }
        </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>




   

