<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <!--Font Awesome-->
      <!--CSS-->
   <link rel="stylesheet" type="text/css" href="style.css">
        <script src="https://kit.fontawesome.com/833591d3ed.js" crossorigin="anonymous"></script>

        <style>
            .texto-info2{
                font-size: 0.9em;
                color: #3a8ab2;
                font-family: Verdana, Arial, sans-serif;
                display: inline-block;
            }
            .nav-item a:hover{
                color: white;
                text-decoration: underline;
            }
        </style>
    
</head>
<body>
<div id="container">

<nav class="navbar navbar-expand-md py-0" id="nav">
    <div class="container">
        <!--Logo-->
        <a href="#" class="navbar-left"><img src="/Front_end/logo.png"></a>

        <div class="d-none d-md-block">
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <a href="/timeline" class="nav-link">Início</a>
                </li>
                <li class="nav-item">
                    <a href="/perfil" class="nav-link">Perfil</a>
                </li>
                <li class="nav-item">
                    <a href="/recados" class="nav-link">Página de recados</a>
                </li>
                <li class="nav-item">
                    <a href="/amigos" class="nav-link">Amigos</a>
                </li>
                <li class="nav-item">
                    <a href="/comunidades" class="nav-link">Comunidades</a>
                </li>
            </ul>
        </div>


        <!--Menu botões para SM-->

        <button class="navbar-toggler ml-auto">
            <span><i class="fas fa-search" style="color:#fff; font-size:28px;"></i></span>
        </button>

        <button onclick="myFunction()" class="navbar-toggler" data-toggle="collapse" data-target="#nav-target2">
            <span class="navbar-toggler-icon"><i class="fas fa-bars"
                    style="color:#fff; font-size:28px;"></i></span>
        </button>

        <!--Navegação-->
        <div class="collapse navbar-collapse ">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <p href="" style="color: #314973;" class="no-margin nav-link d-none d-lg-block">thiagoandre2121@gmail.com</p>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">Sair</a>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link">Pesquisar no orkut</a>
                </li>
            </ul>
        </div>
        
            <div class="collapse navbar-collapse" id="nav-target2">
                <div class="areas d-md-none">
                 <div>
                     <img src="/Front_end/foto-perfil.png" style="margin-left: 30%;" alt="">
                 </div>
                 <div class="campos mt-2">
                     <p class="info-nome p-2" style="text-align: center;">Thiago André</p>
                 </div>

                 <div class="mx-3 my-2">
                    <span><img src="Front_end\icons\inicio.png" alt=""></span>
                     <a href="/timeline">
                         <p class="no-margin texto-info2 ">inicio</p>
                     </a> <br>
                     <span><img src="/Front_end/icons/perfil.png" alt=""></span>
                     <a href="/perfil">
                         <p class="no-margin texto-info2 ">perfil</p>
                     </a> <br>
                     <span><img src="/Front_end/icons/recados.png" alt=""></span>
                     <a href="/recados">
                         <p class="no-margin texto-info2">recados</p>
                     </a> <br>
                     <span><img src="/Front_end/icons/amigos.png" alt=""></span>
                     <a href="/amigos">
                         <p class="no-margin texto-info2 ">amigos</p>
                     </a> <br>
                     <span><img src="/Front_end/icons/comunidades.png" alt=""></span>
                     <a href="/comunidades">
                         <p class="no-margin texto-info2 ">comunidades</p>
                     </a> <br>
                     <span><img src="/Front_end/icons/fotos.png" alt=""></span>
                     <a href="/timeline">
                         <p class="no-margin texto-info2">fotos</p>
                     </a> <br>
                     <span><img src="/Front_end/icons/videos.png" alt=""></span>
                     <a href="/timeline">
                         <p class="no-margin texto-info2">vídeos</p>
                     </a> <br>
                     <span><img src="/Front_end/icons/depoimentos.png" alt=""></span>
                     <a href="/depoimentos">
                         <p class="no-margin texto-info2">depoimentos</p>
                     </a> <br>
                 </div>

                 <div class="campos mx-3 my-2">
                     <div class="mb-2">
                         <h4>Apps</h4>
                         <span><img src="/Front_end/icons/apps.png" alt=""></span>
                         <a href="/timeline">
                             <p class="no-margin texto-info2">adicionar apps</p>
                         </a> <br>
                     </div>
                 </div>
                 <div class=" pb-2 mx-3 my-2" style="border-bottom: 1px solid white;">
                     <div class="mt-2">
                         <span><img src="/Front_end/icons/lista.png" alt=""></span>
                         <a href="/timeline">
                             <p class="no-margin texto-info2">listas</p>
                         </a> <br>
                         <span><img src="/Front_end/icons/atualizaçoes.png" alt=""></span>
                         <a href="/timeline">
                             <p class="no-margin texto-info2">atualizações</p>
                         </a> <br>
                         <span><img src="/Front_end/icons/configuracao.png" alt=""></span>
                         <a href="/timeline">
                             <p class="no-margin texto-info2">configurações</p>
                         </a> <br>
                         <span><img src="/Front_end/icons/sair.png" alt=""></span>
                         <a href="/sair">
                             <p class="no-margin texto-info2">sair</p>
                         </a> <br>
                     </div>
                 </div>
                
                </div>
             </div>
        
    </div>


</div>

    <body>
		<?= $this->content() ?>
	</body>

    <script>
        var x = document.getElementById("nav-target2");
        x.style.display = "none";
        function myFunction() {
          var x = document.getElementById("nav-target2");
          if (x.style.display === "none") {
            x.style.display = "block";
          } else {
            x.style.display = "none";
          }
        }
        </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>




   

